# Generated by Django 4.0.6 on 2022-07-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(default='خالی', max_length=100),
        ),
    ]
